version: '3.1'

services:
    clientapp:
        image: docker.local:5000/q-nomy/clientapp:1.0
        build:
            context: src/client
            dockerfile: webclient.Dockerfile
        ports: 
            - "85:80"
        networks: 
            - local
    
    webapi:
        image: docker.local:5000/q-nomy/webapi:1.0
        build:
            context:  src/server
            dockerfile: webapi.Dockerfile
        environment:
            - DATABASE_SERVER=sqldatabase
            - DATABASE_TYPE=POSTGRES
            - DB_PASSWORD=Password1
            - DB_USER=user01            
        ports:
            - "5000"
            - "5001"
        networks: 
            - local
        depends_on:
            - clientapp
            - sqldatabase

    sqldatabase:
        image: docker.local:5000/q-nomy/sqldatabase:1.0
        build: 
            context: src/server
            dockerfile: sql.Dockerfile
        ports: 
            - "5432"
        networks: 
            local:
                aliases: 
                    - database

networks:
    local:
        driver: bridge