apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete   #Retain
  hostPath:
    path: "/hosthome/alex/minikube_pv_volume"
    # path: "/data/q-nomy-data_pv/"