apiVersion: v1
kind: Service
metadata:
  name: webapi-frontend
  labels:
    app: q-nomy
spec:
    type: NodePort    
    ports:
      - nodePort: 30002
        port: 5000

        # name: "30003-to-5008"
        # nodePort: 30003
        # port: 5008
    selector:
        app: q-nomy
        role: webapi
        q.nomy: webapi
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: q-nomy
    tier: frontend
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q-nomy
      q.nomy: webapi
  strategy: {}
  template:
    metadata:
      labels:
        app: q-nomy
        role: webapi
        q.nomy: webapi
    spec:
      containers:
      - image: webapi:1.0
        imagePullPolicy: "Never"
        name: webapi
        ports:
        - containerPort: 5000
        - containerPort: 5001
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
