version: '3.1'

services:
    clientapp:
        build:
            context: src/client
            dockerfile: webclient.Dockerfile
        ports: 
            - "85:80"
        networks: 
            - local
    
    webapi:
        build:
            context:  src/server
            dockerfile: webapi.Dockerfile
        ports:
            - "5007:5000"
            - "5008:5001"
        networks: 
            - local
        depends_on:
            - clientapp
            - sqldatabase

    sqldatabase:
        build: 
            context: src/server
            dockerfile: sql.Dockerfile
        ports: 
            - "1487:1433"
        networks: 
            local:
                aliases: 
                    - database

networks:
    local:
        driver: bridge