name: Build and push package WebAPI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Package Docker
      run: |
        VERSION=$(date +%s)
        docker login docker.pkg.github.com --username ${GITHUB_ACTOR} --password ${{ secrets.GITHUB_TOKEN }}
        
        # Repository name must be lower-cased :(
        # docker build src/server --file src/server/github.webapi.Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/webapi:${VERSION}
        # docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/webapi:${VERSION}
        
        docker build src/server --file src/server/github.webapi.Dockerfile --tag docker.pkg.github.com/q-nomy/webapi:${VERSION}
        docker push docker.pkg.github.com/q-nomy/webapi:${VERSION}
